services:
  nats:
    image: nats:latest
    command: ["-p", "4222", "-m", "8222", "-js", "-sd", "/var/data"]
    volumes:
      - local:/var/data
    networks:
      - weikio-devcontainer
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - weikio-devcontainer
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  backend:
    image: weikio/backend:dev
    restart: unless-stopped
    environment:
      - 'WEIKIO_HOME=/etc/weikio'
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Weikio__Server__BaseAddress=http://backend/'
      - 'Weikio__Identity__LocalIdentity__IsEnabled=True'
      - 'Weikio__Identity__LocalIdentity__Username=dev@weik.io'
      - 'Weikio__Identity__LocalIdentity__Password=password'
      - 'Weikio__Identity__LocalIdentity__ApiKey=api.key'
      - 'Weikio__Nats__Url=nats://nats:4222'
      - 'ASPNETCORE_URLS=http://*:80'      
    depends_on:
      - nats
    networks:
      - weikio-devcontainer      
    volumes:
      - local:/etc/weikio
    ports:
      - 80      
  ui:
    image: weikio/ui:dev
    restart: unless-stopped
    environment:
      - 'WEIKIO_HOME=/etc/weikio'
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Weikio__Server__BaseAddress=http://backend/'
      - 'ASPNETCORE_URLS=http://*:80'      
    depends_on:
      - backend
    networks:
      - weikio-devcontainer      
    volumes:
      - local:/etc/weikio     
    ports:
      - 80      
  agent:
    image: weikio/agent:dev
    restart: unless-stopped
    environment:
      - 'WEIKIO_HOME=/etc/weikio'
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Weikio__Server__BaseAddress=http://backend/'
      - 'Weikio__Agent__JbangFromPath=true'
      - 'Weikio__Agent__Capabilities__Location=Devcontainer'
      - 'Weikio__Agent__Capabilities__Environment=DevTest'
      - 'Weikio__Nats__Url=nats://nats:4222'
    depends_on:
      - backend
    networks:
      - weikio-devcontainer      
    volumes:
      - local:/etc/weikio       
networks:
  weikio-devcontainer:
volumes:
  local:    